using System;
using System.Windows.Controls;
using DevExpress.AgDataGrid;

namespace AgDataGrid_SortGroupsBySummary {
    public partial class MainPage : UserControl {
        public MainPage() {
            InitializeComponent();
            grid.DataSource = ProductList.GetData();
        }

        private void grid_ColumnsAutoGenerated(object sender, EventArgs e) {
            grid.GroupBy(grid.Columns["Country"]);
            grid.GroupSummarySortInfo.Add(
                new AgDataGridGroupSummarySortInfo(grid.GroupSummary[0], "Country")
                );
        }
    }
}
