Imports Microsoft.VisualBasic
Imports System
Imports System.Windows.Controls
Imports DevExpress.AgDataGrid

Namespace AgDataGrid_SortGroupsBySummary
	Partial Public Class MainPage
		Inherits UserControl
		Public Sub New()
			InitializeComponent()
			grid.DataSource = ProductList.GetData()
		End Sub

		Private Sub grid_ColumnsAutoGenerated(ByVal sender As Object, ByVal e As EventArgs)
			grid.GroupBy(grid.Columns("Country"))
			grid.GroupSummarySortInfo.Add(New AgDataGridGroupSummarySortInfo(grid.GroupSummary(0), "Country"))
		End Sub
	End Class
End Namespace
